#!/user/bin/env groovy
@Library('jenkins-shared-library')
def gv

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "src/script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                 buildJar()
                }
            }
        }

        stage("build and push image") {
            steps {
                script {
                buildImage 'ejones904/demo-app:jma-3.0'
                dockerLogin()
                dockerPush 'ejones904/demo-app:jma-3.0'
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}
